USE mhe_datamsjs;

SHOW TABLES;

SELECT * FROM post;

TRUNCATE TABLE post;

DROP Table post;

CREATE TABLE post (
    id INT AUTO_INCREMENT PRIMARY KEY,
    url VARCHAR(100) NOT NULL UNIQUE,
    titulo VARCHAR(200) NOT NULL,
    resumen VARCHAR(500) NOT NULL,
    contenido TEXT NOT NULL,
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;